language: python
dist: xenial
services:
- docker
python:
  - "3.6"
  - "3.7"
env:
  # jobs running with older Django versions and SQLite
  - DJANGO_REL="django>=2.1,<2.2"
  - DJANGO_REL="django>=2.2,<2.3"
  # jobs running with dependent latest version and specific non-SQLite
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=sqlite
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=mysql
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=mariadb
  - DJANGO_REL="django>=3.0,<3.1" NITRATE_DB=postgres
install: pip install coveralls tox
script:
  - echo running tests
#  - contrib/travis-ci/testrunner.py --python-ver $TRAVIS_PYTHON_VERSION --django-ver "$DJANGO_REL" --nitrate-db ${NITRATE_DB:-sqlite} src/tests
after_success: |
  [ -e .coverage ] && sudo chown travis:travis .coverage && \
    sqlite3 .coverage "UPDATE file SET path = REPLACE(path, '/code', '"$(pwd)"')" && \
    coveralls
jobs:
  include:
    - stage: Misc tests
      name: Lint JavaScript code
      python: "3.7"
      script: |
        docker run --rm -v $PWD:/code:Z -it fedora:32 /bin/bash -c "
          dnf install -y nodejs npm python3-tox
          cd /code
          ls node_modules
          npm install --only=dev eslint@7.1.0
          node node_modules/.bin/eslint \
            src/static/js/testcase_actions.js
        " || :
    - name: Check Python code style
      script: tox -e flake8
    - name: Test build docs
      script: tox -e docs
