language: python
dist: xenial
services:
- docker
matrix:
  include:
  # Matrix of Python 3.6, 3.7 and Django 1.11.x
  - python: "3.6"
    env: DJANGO_REL="django>=1.11,<2.0"
  - python: "3.7"
    env: DJANGO_REL="django>=1.11,<2.0"
  # Matrix of Python 3.6, 3.7 and Django 2.0.x
  - python: "3.6"
    env: DJANGO_REL="django>=2.0,<2.1"
  - python: "3.7"
    env: DJANGO_REL="django>=2.0,<2.1"
  # Matrix of Python 3.6, 3.7 and Django 2.1.x
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<3.0"
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<3.0" NITRATE_DB=mysql
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<3.0" NITRATE_DB=mariadb
  - python: "3.6"
    env: DJANGO_REL="django>=2.1,<3.0" NITRATE_DB=postgres
  - python: "3.7"
    env: DJANGO_REL="django>=2.1,<3.0"
before_install:
- docker pull mysql:5.7
- docker pull mariadb:10.2.21
- docker pull registry.fedoraproject.org/fedora:29
install: pip install coveralls
script:
- contrib/travis-ci/runtests.sh "$(python --version 2>&1)" "$DJANGO_REL" $NITRATE_DB
after_success:
- sudo chown travis:travis .coverage
- sed -i -e s@/code@"$(pwd)"@g .coverage
- coveralls
notifications:
  email:
    on_failure: change
    on_success: change
