name: Renovate

on:
  schedule:
    - cron: '50 14 * * *'

jobs:
  linters:
    name: Run renovate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: renovatebot/github-action@v39.1.3
        with:
          renovate-version: 37.68.3
          token: ${{ secrets.RENOVATE_TOKEN }}
