name: Distribute latest image

on:
  push:
    branches:
      - develop

jobs:
  build-push-develop-images:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    name: Build and push develop images
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install -y make python3-build python3-venv podman
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: Nitrate/containers
      - name: Build all images and push them to registry
        run: |
          echo "${{ secrets.quay_token }}" | \
            docker login -u "${{ secrets.quay_username }}" --password-stdin quay.io
          make all-images push-all
