name: Unit Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  unittests:
    name: "py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.db }}"
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 7
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12']
        django-version: [django420]
        db: [sqlite]
        include:
          - python-version: '3.12'
            django-version: django420
            db: mysql
          - python-version: '3.12'
            django-version: django420
            db: mariadb
          - python-version: '3.12'
            django-version: django420
            db: postgres

    steps:
      - name: Install packages used to setup testenv
        run: |
          sudo apt update
          sudo apt-get install -y jq make gcc python3-dev libkrb5-dev libmariadb-dev libcrypt-dev

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the tests
        env:
          TEST_DB_ENGINE: ${{ matrix.db }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          set -eu
          set -o pipefail

          python3 -m pip install --upgrade pip
          python3 -m pip install tox coveralls

          python3 -m pip --version
          tox -l

          start_test_db() {
            make start-testdb-${TEST_DB_ENGINE} detach=yes
            trap 'make stop-testdb-${TEST_DB_ENGINE}' EXIT ERR
            make check-testdb-health db_engine=${TEST_DB_ENGINE}
          }

          [ "x$TEST_DB_ENGINE" = "xsqlite" ] || start_test_db
          tox -e py${PYTHON_VERSION/./}-${PYTHON_VERSION}-${TEST_DB_ENGINE}

      - name: Parallel coverage report
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: testenv-py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.db }}
          parallel: true

  coveralls:
    name: Finish Coveralls
    needs: unittests
    runs-on: ubuntu-latest
    steps:
      - name: Finish coverage report
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
